package com.turnos.drools

import com.turnos.drools.data.*;

// Sumamos el importe total de los productos

dialect "mvel"

// Comprobamos si la obra social del turno es OSMATA, si es así aplicamos un 50% de descuento
rule "OSMATA rule"
	salience 15
	when
        cierre : Cierre ();
        obraSocial : ObraSocial ( nombre == "OSMATA") from cierre.getTurnos().getObraSocial(); 
    then
        cierre.setMontoCubiertoObrasSociales(cierre.getMontoCubiertoObrasSociales() * (1 - (50 / 100d) ) );
        cierre.setMontoSinCubrir( cierre.getMontoTotal() - cierre.getMontoCubiertoObrasSociales());
end

// Comprobamos si la obra social del turno es OSPE, si es así aplicamos un 80% de descuento
rule "OSPE rule"
	salience 15
	when
        cierre : Cierre ();
        obraSocial : ObraSocial ( nombre == "OSPE") from cierre.getTurnos().getObraSocial(); 
    then
        cierre.setMontoCubiertoObrasSociales(cierre.getMontoCubiertoObrasSociales() * (1 - (20 / 100d) ) );
        cierre.setMontoSinCubrir( cierre.getMontoTotal() - cierre.getMontoCubiertoObrasSociales());
end

// Comprobamos si la obra social del turno es OSPE, si es así aplicamos un 70% de descuento
rule "OSPE rule not active"
	salience 10
	when
        cierre : Cierre ();
        obraSocial : ObraSocial ( nombre == "OSPE") from cierre.getTurnos().getObraSocial(); 
    then
        cierre.setMontoCubiertoObrasSociales(cierre.getMontoCubiertoObrasSociales() * (1 - (30 / 100d) ) );
        cierre.setMontoSinCubrir( cierre.getMontoTotal() - cierre.getMontoCubiertoObrasSociales());
end

// Comprobamos si la obra social del turno es OSDE, si es así aplicamos un 30% de descuento
rule "OSDE rule"
	salience 15
	when
        cierre : Cierre ();
        obraSocial : ObraSocial ( nombre == "OSDE") from cierre.getTurnos().getObraSocial(); 
    then
        cierre.setMontoCubiertoObrasSociales(cierre.getMontoCubiertoObrasSociales() * (1 - (70 / 100d) ) );
        cierre.setMontoSinCubrir( cierre.getMontoTotal() - cierre.getMontoCubiertoObrasSociales());
end

// Comprobamos si la obra social del turno es OSPIA, si es así aplicamos un 23% de descuento
rule "OSPIA rule"
	salience 15
	when
        cierre : Cierre ();
        obraSocial : ObraSocial ( nombre == "OSPIA") from cierre.getTurnos().getObraSocial(); 
    then
        cierre.setMontoCubiertoObrasSociales(cierre.getMontoCubiertoObrasSociales() * (1 - (77 / 100d) ) );
        cierre.setMontoSinCubrir( cierre.getMontoTotal() - cierre.getMontoCubiertoObrasSociales());
end

// Comprobamos si la obra social del turno es PAMI, si es así aplicamos un 21% de descuento
rule "PAMI rule"
	salience 15
	when
        cierre : Cierre ();
        obraSocial : ObraSocial ( nombre == "PAMI") from cierre.getTurnos().getObraSocial(); 
    then
        cierre.setMontoCubiertoObrasSociales(cierre.getMontoCubiertoObrasSociales() * (1 - (79 / 100d) ) );
        cierre.setMontoSinCubrir( cierre.getMontoTotal() - cierre.getMontoCubiertoObrasSociales());
end

// Comprobamos si la obra social del turno es OSPIP, si es así aplicamos un 95% de descuento
rule "OSPIP rule"
	salience 15
	when
        cierre : Cierre ();
        obraSocial : ObraSocial ( nombre == "OSPIP") from cierre.getTurnos().getObraSocial(); 
    then
        cierre.setMontoCubiertoObrasSociales(cierre.getMontoCubiertoObrasSociales() * (1 - (5 / 100d) ) );
        cierre.setMontoSinCubrir( cierre.getMontoTotal() - cierre.getMontoCubiertoObrasSociales());
end

